// Turkiye il / ilce / mahalle verisi (ornek - genis liste)
const adresData = {
  "Adana": {
    "Seyhan": ["Adnan Menderes Mah.", "Barbaros Mah.", "Cemaltas Mah.", "Cumhuriyet Mah.", "Denizli Mah.", "Emek Mah.", "Guzelce Mah.", "Huzur Mah.", "Inonü Mah.", "Kurtulus Mah.", "Merkez Mah.", "Yeni Mah."],
    "Yuregir": ["Abidinpasa Mah.", "Baraj Mah.", "Canturk Mah.", "Demetevler Mah.", "Ege Mah.", "Fevzi Cakmak Mah."],
    "Cukurova": ["Baraj Mah.", "Celiktas Mah.", "Gundogdu Mah.", "Incirlik Mah.", "Sarıcam Mah."],
    "Saricam": ["Ataturk Mah.", "Baris Mah.", "Cumhuriyet Mah.", "Karasoku Mah."]
  },
  "Ankara": {
    "Cankaya": ["Ayranci Mah.", "Balgat Mah.", "Bahcelievler Mah.", "Cebeci Mah.", "Dikmen Mah.", "Emek Mah.", "Gaziosmanpasa Mah.", "Guneykent Mah.", "Korfez Mah.", "Merasim Mah.", "Oran Mah.", "Tunali Hilmi Mah.", "Yenimahalle Mah."],
    "Kecioren": ["Aktepe Mah.", "Bademlidere Mah.", "BaglarbasI Mah.", "Cumhuriyet Mah.", "Dutluk Mah.", "Esertepe Mah.", "Eryaman Mah.", "Kalaba Mah.", "Pinar Mah.", "Ovecler Mah."],
    "Mamak": ["Altindag Mah.", "Ayranci Mah.", "Balkanca Mah.", "Bogazici Mah.", "Demirlibahce Mah.", "Ege Mah.", "Firat Mah.", "Hatipoglu Mah."],
    "Etimesgut": ["Ataturk Mah.", "Baris Mah.", "Elvankent Mah.", "Gulveren Mah.", "Mavikent Mah.", "Piyangotepe Mah."],
    "Sincan": ["Ataturk Mah.", "Baglar Mah.", "Cumhuriyet Mah.", "Depo Mah.", "Istiklal Mah.", "Saraykoy Mah."],
    "Yenimahalle": ["Akdere Mah.", "Batikent Mah.", "Emniyet Mah.", "Gimat Mah.", "Kartaltepe Mah.", "Susuzköy Mah.", "Yildiz Mah."]
  },
  "Istanbul": {
    "Kadikoy": ["Acıbadem Mah.", "Bostancı Mah.", "Caferaga Mah.", "Erenköy Mah.", "Fenerbahce Mah.", "Goztepe Mah.", "Hasanpasa Mah.", "Koşuyolu Mah.", "Moda Mah.", "Rasimpasa Mah.", "Suadiye Mah."],
    "Besiktas": ["Abbasaga Mah.", "Akaretler Mah.", "Arnavutköy Mah.", "Balmumcu Mah.", "Bebek Mah.", "Etiler Mah.", "Gayrettepe Mah.", "Kuruçesme Mah.", "Levazim Mah.", "Ortaköy Mah."],
    "Sisli": ["Bozkurt Mah.", "Cumhuriyet Mah.", "Esentepe Mah.", "Feriköy Mah.", "Fulya Mah.", "Gülbahar Mah.", "Harbiye Mah.", "Mecidiyeköy Mah.", "Pangaltı Mah.", "Sisli Mah."],
    "Uskudar": ["Altunizade Mah.", "Baglarbasi Mah.", "Beylerbeyi Mah.", "Çavusdere Mah.", "Küplüce Mah.", "Mimar Sinan Mah.", "Selami Ali Mah.", "Üsküdar Merkez Mah."]
  },
  "Izmir": {
    "Konak": ["Alsancak Mah.", "Basmane Mah.", "Çinarlı Mah.", "Dagkapi Mah.", "Eges Mah.", "Garirbceli Mah.", "Kazimdirik Mah.", "Kültürpark Mah.", "Mithatpasa Mah."],
    "Karsiyaka": ["Ataturk Mah.", "Bahcelievler Mah.", "Bostanli Mah.", "Cumhuriyet Mah.", "Donanmacı Mah.", "Fevzipasa Mah.", "Goncalar Mah."],
    "Bornova": ["Atatürk Mah.", "Ergenekon Mah.", "Gazi Mah.", "Kucukpark Mah.", "Manavkuyu Mah.", "Sanayi Mah.", "Yesilova Mah."]
  },
  "Sanliurfa": {
    "Haliliye": ["Selahaddin Eyyubi Mah.", "Abbasoglu Mah.", "Akcakale Mah.", "Akdogmus Mah.", "Aktoprak Mah.", "Akyüz Mah.", "Alibahsi Mah.", "Alicetinkaya Mah.", "Altinbasak Mah.", "Aricilik Mah.", "Asriye Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Balikligol Mah.", "Bamyalik Mah.", "Baris Mah.", "Bozkaya Mah.", "Buyukdere Mah.", "Camkolu Mah.", "Cengizhan Mah.", "Cumhuriyet Mah.", "Dede Mah.", "Demirkapi Mah.", "Divan Mah.", "Doganli Mah.", "Egemen Mah.", "Emirsultan Mah.", "Etüd Mah.", "Fatih Mah.", "Ferhat Mah.", "Güvençli Mah.", "Hamidiye Mah.", "Hasan Padisah Mah.", "Kanallar Mah.", "Kasimiye Mah.", "Kutlubey Mah.", "Mevlid-i Halil Mah.", "Mutluluk Mah.", "Namik Kemal Mah.", "Nizip Cad. Mah.", "Oguzeli Mah.", "Ortaigdeli Mah.", "Parmakli Mah.", "Sarayonu Mah.", "Sofular Mah.", "Uculer Mah.", "Ugurlu Mah.", "Viransehir Mah.", "Yeni Mah.", "Yenibahce Mah.", "Yesilyurt Mah."],
    "Eyyubiye": ["Akyurt Mah.", "Atatürk Mah.", "Bahcelievler Mah.", "Batikent Mah.", "Cumhuriyet Mah.", "Dede Mah.", "Demirkapi Mah.", "Dogankent Mah.", "Emekci Mah.", "Fevzi Cakmak Mah.", "Iskender Pasa Mah.", "Karakoyun Mah.", "Karatas Mah.", "Kibris Mah.", "Kozluk Mah.", "Merkez Mah.", "Sumer Mah.", "Ulubatli Mah.", "Yavuz Selim Mah.", "Yenicami Mah."],
    "Karakopru": ["Ali Fuat Cebesoy Mah.", "Ataturk Mah.", "Cumhuriyet Mah.", "Dikbiyik Mah.", "Duzova Mah.", "Firuzlu Mah.", "Gazi Mah.", "Hamzapinar Mah.", "Kazim Karabekir Mah.", "Mehmetcik Mah.", "Nalbantoglu Mah.", "Nehriye Mah.", "Öz Mah.", "Pamukcular Mah.", "Sozeri Mah.", "Yakatarla Mah.", "Ziyaret Mah."],
    "Hilvan": ["Merkez Mah.", "Bahcelievler Mah.", "Camili Mah.", "Cumhuriyet Mah.", "Eski Mah.", "Korucu Mah.", "Yeni Mah."],
    "Siverek": ["Bahcelievler Mah.", "Barindik Mah.", "Cumhuriyet Mah.", "Dogan Mah.", "Emekci Mah.", "Fatih Mah.", "Fevzipasa Mah.", "Gazi Mah.", "Koyuncu Mah.", "Merkez Mah.", "Saray Mah.", "Yeni Mah."],
    "Suruc": ["Merkez Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Cumhuriyet Mah."],
    "Viransehir": ["Ataturk Mah.", "Bahcelievler Mah.", "Cumhuriyet Mah.", "Kurtulus Mah.", "Merkez Mah.", "Saraycik Mah."],
    "Bozova": ["Merkez Mah.", "Cumhuriyet Mah.", "Ataturk Mah."],
    "Ceylanpinar": ["Merkez Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Cumhuriyet Mah."]
  },
  "Bursa": {
    "Nilufer": ["Adliye Mah.", "Altınkent Mah.", "Ataevler Mah.", "Bahcelievler Mah.", "Beşevler Mah.", "Demirtas Mah.", "Egitim Mah.", "Fethiye Mah.", "Görükle Mah.", "Karaman Mah.", "Odunluk Mah.", "Ozluce Mah."],
    "Osmangazi": ["Alibey Mah.", "Babatorini Mah.", "Bahcelievler Mah.", "Bademlik Mah.", "Burç Mah.", "Cumhuriyet Mah.", "Dobruca Mah.", "Emek Mah.", "Hamitler Mah.", "Ihsaniye Mah."],
    "Yildirim": ["Akpinar Mah.", "Ataturk Mah.", "Bademlik Mah.", "Dere Mah.", "Emir Sultan Mah.", "Güneş Mah.", "Kale Mah.", "Mimar Sinan Mah.", "Namazgah Mah."]
  },
  "Adiyaman": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Karagol Mah.", "Merkez Mah.", "Yeni Mah."], "Golbasi": ["Merkez Mah.", "Cumhuriyet Mah."], "Besni": ["Merkez Mah.", "Cumhuriyet Mah."] },
  "Afyonkarahisar": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Karagol Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Agri": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Karagol Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Aksaray": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Karagol Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Amasya": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Karagol Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Ardahan": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Artvin": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Aydin": { "Efeler": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Fatih Mah.", "Orta Mah.", "Yeni Mah."], "Kusadasi": ["Ataturk Mah.", "Cumhuriyet Mah.", "Merkez Mah."] },
  "Balikesir": { "Altieylul": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."], "Karesi": ["Cumhuriyet Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Batman": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Yenisehir Mah.", "Merkez Mah."] },
  "Bayburt": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Bilecik": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Bingol": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Yeni Mah.", "Merkez Mah."] },
  "Bitlis": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Bolu": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Burdur": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Canakkale": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah."] },
  "Cankiri": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Corum": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Gazi Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Denizli": { "Pamukkale": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."], "Merkezefendi": ["Cumhuriyet Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Diyarbakir": { "Baglar": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Yeni Mah.", "Merkez Mah."], "Kayapinar": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."], "Sur": ["Cumhuriyet Mah.", "Fatih Mah.", "Merkez Mah."] },
  "Duzce": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Edirne": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Elazig": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Erzincan": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Erzurum": { "Palandoken": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah."], "Yakutiye": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Eskisehir": { "Odunpazari": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."], "Tepebaşı": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Gaziantep": { "Sahinbey": ["Ataturk Mah.", "Bahcelievler Mah.", "Beylerbeyi Mah.", "Bulent Ecevit Mah.", "Cumhuriyet Mah.", "Fatih Mah.", "Gazikent Mah.", "Gazi Mah.", "Kocatepe Mah.", "Kurtulus Mah.", "Merkez Mah.", "Mujde Mah."], "Sehitkamil": ["Ataturk Mah.", "Bahcelievler Mah.", "Cumhuriyet Mah.", "Fatih Mah.", "Karagoz Mah.", "Merkez Mah.", "Yavuz Mah.", "Yenisehir Mah."] },
  "Giresun": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Gumushane": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Hakkari": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Hatay": { "Antakya": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."], "Iskenderun": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah."] },
  "Igdir": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Isparta": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Kahramanmaras": { "Dulkadiroglu": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."], "Onikisubat": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Karabuk": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Karaman": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Kars": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Kastamonu": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Kayseri": { "Kocasinan": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."], "Melikgazi": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah."] },
  "Kilis": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah."] },
  "Kirikkale": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Kirklareli": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Kirsehir": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Kocaeli": { "Izmit": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."], "Gebze": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Konya": { "Karatay": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."], "Meram": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah."], "Selcuklu": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Kule Mah.", "Merkez Mah."] },
  "Kutahya": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Malatya": { "Battalgazi": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Hamidiye Mah.", "Merkez Mah.", "Yeni Mah."], "Yesiltepe": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Manisa": { "Sehzadeler": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."], "Yunusemre": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Mardin": { "Artuklu": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Mersin": { "Akdeniz": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah."], "Mezitli": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."], "Toroslar": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."], "Yenisehir": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Mugla": { "Menteşe": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."], "Bodrum": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Mus": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Nevsehir": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Nigde": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Ordu": { "Altinordu": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Osmaniye": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah."] },
  "Rize": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Sakarya": { "Adapazari": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."], "Serdivan": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Samsun": { "Ilkadim": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."], "Canik": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Siirt": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Sinop": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Sirnak": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Sivas": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Tekirdag": { "Süleymanpasa": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Tokat": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Trabzon": { "Ortahisar": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Iskenderli Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Tunceli": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Usak": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Van": { "Ipekyolu": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah."], "Tusba": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah."] },
  "Yalova": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Yozgat": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Fatih Mah.", "Merkez Mah.", "Yeni Mah."] },
  "Zonguldak": { "Merkez": ["Cumhuriyet Mah.", "Ataturk Mah.", "Bahcelievler Mah.", "Merkez Mah.", "Yeni Mah."] }
};

module.exports = adresData;
